// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPhlNuiR03Rc0WsT8NtbksJtlKfWJb_yQ',
    appId: '1:793576467691:web:990225f704c1847beaa2ae',
    messagingSenderId: '793576467691',
    projectId: 'mobdevindividualassignment2',
    authDomain: 'mobdevindividualassignment2.firebaseapp.com',
    storageBucket: 'mobdevindividualassignment2.firebasestorage.app',
    measurementId: 'G-F5BYPHVJNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsGJOR86dio--ShoGpSViiVZFcJsYmITU',
    appId: '1:793576467691:android:c7f4235737d58795eaa2ae',
    messagingSenderId: '793576467691',
    projectId: 'mobdevindividualassignment2',
    storageBucket: 'mobdevindividualassignment2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjB6aa8UO7Mg7u6uUzHtheZFe9aY1KMUo',
    appId: '1:793576467691:ios:de026103fb5cb0e3eaa2ae',
    messagingSenderId: '793576467691',
    projectId: 'mobdevindividualassignment2',
    storageBucket: 'mobdevindividualassignment2.firebasestorage.app',
    iosBundleId: 'com.example.individualAssignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjB6aa8UO7Mg7u6uUzHtheZFe9aY1KMUo',
    appId: '1:793576467691:ios:de026103fb5cb0e3eaa2ae',
    messagingSenderId: '793576467691',
    projectId: 'mobdevindividualassignment2',
    storageBucket: 'mobdevindividualassignment2.firebasestorage.app',
    iosBundleId: 'com.example.individualAssignment2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPhlNuiR03Rc0WsT8NtbksJtlKfWJb_yQ',
    appId: '1:793576467691:web:d93bed480fc65be6eaa2ae',
    messagingSenderId: '793576467691',
    projectId: 'mobdevindividualassignment2',
    authDomain: 'mobdevindividualassignment2.firebaseapp.com',
    storageBucket: 'mobdevindividualassignment2.firebasestorage.app',
    measurementId: 'G-3WDPXP74NE',
  );
}
